export const APP_NAME = "Esnaf Tezgahı"

export const ROUTES = {
  DASHBOARD: "/",
  UPLOAD: "/upload",
  INVENTORY: "/inventory",
  ORDERS: "/orders",
  SETTINGS: "/settings",
}

export const SOURCE_LABELS = {
  image_order: "GÖRÜNTÜ",
  voice: "SES",
  manual: "MANUEL",
}

export const STATUS_LABELS = {
  pending: "Bekliyor",
  fulfilled: "Tamamlandı",
  cancelled: "İptal",
}

export const STOCK_STATUS_LABELS = {
  ok: "Normal",
  low: "Düşük",
  critical: "Kritik",
}

export const ALERT_TYPE_LABELS = {
  low_stock: "Düşük Stok",
  critical_stock: "Kritik Stok",
  setup_required: "Kurulum Gerekli",
}

export const T = {
  tr: {
    dashboard: "Panel",
    upload: "Yükle",
    inventory: "Stok",
    orders: "Siparişler",
    settings: "Ayarlar",
    newOrder: "Yeni Sipariş",
    searchPlaceholder: "Stok ara (Enter'a bas)...",
    activeAlerts: "Aktif Uyarılar",
    agentActivity: "Ajan Aktivitesi",
    notifications: "Bildirimler",
    noAlerts: "Aktif uyarı yok. Her şey yolunda!",
    viewAll: "Panelde Tümünü Gör",
    ordersToday: "Bugünkü Siparişler",
    noActivity: "Henüz ajan aktivitesi yok. Sipariş fişi veya raf fotoğrafı yükle.",
    dismiss: "Kapat",
    email: "E-posta",
    allClear: "Tümü Tamam",
    orderSlip: "Sipariş Fişi",
    shelfScan: "Raf Tarama",
    voiceNote: "Sesli Not",
    orderSlipDesc: "JPG, PNG veya WEBP - el yazısı veya baskı",
    shelfScanDesc: "Depo rafı veya ürün teşhir fotoğrafı",
    voiceNoteDesc: "WAV, MP3 veya M4A - Türkçe veya İngilizce konuş",
    uploadTitle: "Yükle",
    uploadDesc: "Sipariş fişi, raf fotoğrafı veya sesli not bırak - gerisini ajan halleder.",
    importCsv: "CSV İçe Aktar",
    addProduct: "Ürün Ekle",
    totalProducts: "toplam ürün",
    totalOrders: "toplam sipariş",
    product: "Ürün",
    sku: "SKU",
    category: "Kategori",
    price: "Fiyat",
    stock: "Stok",
    threshold: "Eşik",
    status: "Durum",
    qty: "Adet",
    unitPrice: "Birim Fiyat",
  },
  en: {
    dashboard: "Dashboard",
    upload: "Upload",
    inventory: "Inventory",
    orders: "Orders",
    settings: "Settings",
    newOrder: "New Order",
    searchPlaceholder: "Search inventory (press Enter)...",
    activeAlerts: "Active Alerts",
    agentActivity: "Agent Activity",
    notifications: "Notifications",
    noAlerts: "No active alerts. All clear!",
    viewAll: "View All on Dashboard",
    ordersToday: "Orders Today",
    noActivity: "No agent activity yet. Upload an order slip or shelf photo to get started.",
    dismiss: "Dismiss",
    email: "Email",
    allClear: "All Clear",
    orderSlip: "Order Slip",
    shelfScan: "Shelf Scan",
    voiceNote: "Voice Note",
    orderSlipDesc: "JPG, PNG, or WEBP - handwritten or printed",
    shelfScanDesc: "Photo of your storage shelf or product display",
    voiceNoteDesc: "WAV, MP3, or M4A - speak in Turkish or English",
    uploadTitle: "Upload",
    uploadDesc: "Drop an order slip, shelf photo, or voice note - the agent handles the rest.",
    importCsv: "Import CSV",
    addProduct: "Add Product",
    totalProducts: "total products",
    totalOrders: "total orders",
    product: "Product",
    sku: "SKU",
    category: "Category",
    price: "Price",
    stock: "Stock",
    threshold: "Threshold",
    status: "Status",
    qty: "Qty",
    unitPrice: "Unit Price",
  }
}
